/*
Copyright (c) 2006-2008, Guillaume Pothier
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this 
      list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, 
      this list of conditions and the following disclaimer in the documentation 
      and/or other materials provided with the distribution.
    * Neither the name of the University of Chile nor the names of its contributors 
      may be used to endorse or promote products derived from this software without 
      specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY 
EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT 
NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
POSSIBILITY OF SUCH DAMAGE.

Parts of this work rely on the MD5 algorithm "derived from the RSA Data Security, 
Inc. MD5 Message-Digest Algorithm".
*/
package tod.core.database.event;

import tod.core.database.browser.IEventBrowser;

/**
 * An event that contains other events.
 * @author gpothier
 */
public interface IParentEvent extends ILogEvent
{
	/**
	 * Returns an {@link IEventBrowser} that permits to retrieve the
	 * children of this event.
	 */
	public IEventBrowser getChildrenBrowser();
	
	/**
	 * Indicates if this node has children apart from the exit event.
	 */
	public boolean hasRealChildren();

	
	/**
	 * Indicates if this event is the direct parent of its children.
	 * A call to an instrumented behavior from another instrumented
	 * behavior results in a direct parent event: children events are
	 * those that occur during the execution of the called behavior.
	 * <br/>
	 * On the other hand, call to a non-instrumented behavior from
	 * an instrumented behavior results in an indirect parent event:
	 * the non-instrumented behavior will not generate any event, but it
	 * might call an instrumented behavior; the events generated by the latter
	 * will appear as children of the parent event, although they occured
	 * deeper in the control flow.
	 */
	public boolean isDirectParent();

	/**
	 * Returns the timestamp of the first event of the set of events
	 * comprised of this container and its contained events.
	 */
	public long getFirstTimestamp();
	
	/**
	 * Returns the timestamp of the last event of the set of events
	 * comprised of this container and its contained events.
	 */
	public long getLastTimestamp();
}
