/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tod_core_ObjectIdentity */

#ifndef _Included_tod_core_ObjectIdentity
#define _Included_tod_core_ObjectIdentity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tod_core_ObjectIdentity
 * Method:    get
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_tod_core_ObjectIdentity_get
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
