/*
 * Created on Oct 16, 2004
 */
package tod.core.transport;

/**
 * @author gpothier
 */
public enum MessageType
{
	// Events
	INSTANTIATION,
	CONSTRUCTOR_CHAINING,
	BEFORE_METHOD_CALL,
	AFTER_METHOD_CALL,
	AFTER_METHOD_CALL_WITH_EXCEPTION,
	BEFORE_METHOD_CALL_DRY,
	AFTER_METHOD_CALL_DRY,
	BEHAVIOR_ENTER,
	BEHAVIOR_EXIT,
	BEHAVIOR_EXIT_WITH_EXCEPTION,
	EXCEPTION_GENERATED,
	FIELD_WRITE,
	LOCAL_VARIABLE_WRITE,
	OUTPUT,
	
	//Arguments
	OBJECT_ARRAY, SIMPLE_OBJECT, NONE,
	
	// Argument values
	NULL, BOOLEAN, BYTE, CHAR, INT, LONG, FLOAT, DOUBLE, STRING, 
	OBJECT_UID, OBJECT_HASH,
	
	// Registering
	REGISTER_CLASS, REGISTER_BEHAVIOR, REGISTER_FIELD, 
	REGISTER_FILE, REGISTER_THREAD, REGISTER_LOCAL_VARIABLE,
    REGISTER_BEHAVIOR_ATTRIBUTES
}
