/*
 * Created on Oct 16, 2004
 */
package tod.core.transport;

/**
 * @author gpothier
 */
public enum MessageType
{
	// Events
	INSTANTIATION,
	SUPER_CALL,
	METHOD_CALL,
	BEHAVIOR_EXIT,
	EXCEPTION,
	FIELD_WRITE,
	ARRAY_WRITE,
	LOCAL_VARIABLE_WRITE,
	OUTPUT,
	
	//Arguments
	OBJECT_ARRAY, SIMPLE_OBJECT, NONE,
	
	// Argument values
	NULL, BOOLEAN, BYTE, CHAR, SHORT, INT, LONG, FLOAT, DOUBLE, STRING, 
	OBJECT_UID, OBJECT_HASH,
	
	// Registering
	REGISTER_CLASS, REGISTER_BEHAVIOR, REGISTER_FIELD, 
	REGISTER_FILE, REGISTER_THREAD, REGISTER_LOCAL_VARIABLE,
    REGISTER_BEHAVIOR_ATTRIBUTES
}
