/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tod_core_EventInterpreter_ThreadData */

#ifndef _Included_tod_core_EventInterpreter_ThreadData
#define _Included_tod_core_EventInterpreter_ThreadData
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
