/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tod_core_EventInterpreter_FrameInfo */

#ifndef _Included_tod_core_EventInterpreter_FrameInfo
#define _Included_tod_core_EventInterpreter_FrameInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
