/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tod_core_EventInterpreter */

#ifndef _Included_tod_core_EventInterpreter
#define _Included_tod_core_EventInterpreter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tod_core_EventInterpreter
 * Method:    getHostId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_tod_core_EventInterpreter_getHostId
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
