#! /bin/sh


export NATIVE=..

[ -n "$LIB_DIR" ] || export LIB_DIR=../lib
[ -n "$BUILD_DIR" ] || export BUILD_DIR=../build

export CLASSPATH=.:$LIB_DIR/asm-2.1.jar:$LIB_DIR/asm-commons-2.1.jar\
:$LIB_DIR/backport-util-concurrent.jar:$LIB_DIR/javassist.jar\
:$LIB_DIR/retrotranslator-runtime-1.0.8.jar:$LIB_DIR/retrotranslator-transformer-1.0.8.jar\
:$BUILD_DIR/tod-agent.jar:$BUILD_DIR/tod-debugger.jar:$BUILD_DIR/tod-test.jar\
:$LIB_DIR/zz.utils.jar

[ -n "$MASTER_HOST" ] || export MASTER_HOST=syntagma
export DATA_DIR=$LOCAL_STORAGE/tod
export EVENTS_FILE=$SHARED_STORAGE/tod/events-raw.bin
export LOCATIONS_FILE=$SHARED_STORAGE/tod/locations.bin