#! /bin/sh


export NATIVE=..

[ -n "$LIB_DIR" ] || export LIB_DIR=../lib
[ -n "$BUILD_DIR" ] || export BUILD_DIR=../build

export CLASSPATH=.:$LIB_DIR/asm-2.1.jar:$LIB_DIR/asm-commons-2.1.jar\
:$LIB_DIR/backport-util-concurrent.jar:$LIB_DIR/javassist.jar\
:$LIB_DIR/retrotranslator-runtime-1.0.8.jar:$LIB_DIR/retrotranslator-transformer-1.0.8.jar\
:$BUILD_DIR/tod-agent.jar:$BUILD_DIR/tod-debugger.jar:$BUILD_DIR/tod-test.jar\
:$LIB_DIR/zz.utils.jar

[ -n "$MASTER_HOST" ] || export MASTER_HOST=syntagma

[ -n "$DATA_DIR" ] || export DATA_DIR=$LOCAL_STORAGE/tod
[ -n "$EVENTS_FILE" ] || export EVENTS_FILE=$SHARED_STORAGE/tod/events-raw.bin
export LOCATIONS_FILE=$SHARED_STORAGE/tod/locations.bin

[ -n "$PAGE_BUFFER_SIZE" ] || export PAGE_BUFFER_SIZE=200m
[ -n "$JVM_HEAP_SIZE_SIZE" ] || export JVM_HEAP_SIZE_SIZE=500m
[ -n "$SUB_FACTOR" ] || export SUB_FACTOR=2
[ -n "$GRID_IMPL" ] || export GRID_IMPL="uniform"

# LOCK_FILE=$LOCAL_STORAGE/tod/lock
