/* Generated By:JavaCC: Do not edit this line. WorkingSetParserConstants.java */
package tod.tools.parsers;

public interface WorkingSetParserConstants
{

    int EOF = 0;

    int PLUS = 1;

    int MINUS = 2;

    int LBRACKET = 3;

    int RBRACKET = 4;

    int DOT = 5;

    int STAR = 6;

    int COLON = 7;

    int CLASSNAME = 8;

    int ID = 9;

    int IDCHAR = 10;

    int DEFAULT = 0;

    String[] tokenImage =
        { "<EOF>", "\"+\"", "\"-\"", "\"[\"", "\"]\"", "\".\"", "\"*\"", "\":\"", "<CLASSNAME>", "<ID>", "<IDCHAR>",
         "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"", };

}
